version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - OPENAI_API_KEY=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
    volumes:
      - ./settings.js:/var/chatgpt-api/settings.js:cached
    ports:
      - '${APP_PORT:-3000}:3000'
